
language: generic 
sudo:     required

services:
  - docker

before_install:
  - docker build -t guimaron/fibonacci-frontend-test -f ./frontend/Dockerfile.dev ./frontend

script:
  # TESTS
  - docker run -e CI=true guimaron/fibonacci-frontend-test npm test

after_success:
# building .env in ./api
  - chmod u+x ./api/build-env.sh
  - touch ./api/build-env.sh
  - ./api/build-env.sh
  - cat ./api/.env
  # building .env in ./worker
  - chmod u+x ./worker/build-env.sh
  - touch ./worker/build-env.sh
  - ./worker/build-env.sh
  - cat ./worker/.env
  # Building Docker images
  - docker build -t guimaron/fibonacci-api      ./api
  - docker build -t guimaron/fibonacci-frontend ./frontend
  - docker build -t guimaron/fibonacci-nginx    ./nginx
  - docker build -t guimaron/fibonacci-worker   ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Pushing images do DockHub
  - docker push guimaron/fibonacci-api
  - docker push guimaron/fibonacci-frontend
  - docker push guimaron/fibonacci-nginx
  - docker push guimaron/fibonacci-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'fibonacci-app'
  env: 'Fibonacciapp-env-1'
  bucket_name: 'elasticbeanstalk-us-east-1-542898700754'
  bucket_path: 'fibonacci-app'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
