version:  '3'

services:
 
  api:
    build:
      dockerfile: 'Dockerfile.dev'
      context:    './api'
    volumes:
      - '/usr/app/node_modules'
      - './api:/usr/app'
    environment:
      - REACT_APP_REDIS_HOST=redis
      - REACT_APP_REDIS_PORT=6379
      - REACT_APP_PGHOST=postgres
      - REACT_APP_PGPORT=5432
      - REACT_APP_PGUSER=postgres
      - REACT_APP_PGPASSWORD=postgres_password
      - REACT_APP_PGDATABASE=postgres
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      dockerfile: 'Dockerfile.dev'
      context:    './frontend'
    environment:
      - WDS_SOCKET_PORT=0    
    volumes:
      - '/usr/app/node_modules'
      - './frontend:/usr/app'
    depends_on:
      - api

  nginx:
    build:
      dockerfile: 'Dockerfile.dev'
      context:    './nginx'
    restart:  always
    ports:
      - "80:80"
    depends_on:
      - api
      - frontend

  postgres:
    image:  'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password

  redis:
    image:  'redis:latest'

  worker:
    build:
      dockerfile: 'Dockerfile.dev'
      context:    './worker'
    volumes:
      - '/usr/app/node_modules'
      - './worker:/usr/app'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
